webvitinh/Areas/Admin/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Model;
using Model.Dao;
using OnlineShop.Areas.Admin.Controllers;
using webvitinh.Common;

namespace webvitinh.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("Admin/[controller]")]
    public class ProductController : BaseController
    {
        OnlineShop1Context db = null;
        public ProductController()
        {
            db = new OnlineShop1Context();
        }

        [Route("[action]")]
        public IActionResult Index()
        {
            var model = new ProductDao();
            var result = model.GetAllProduct();
            return View(result);
        }

        [Route("[action]")]
        public IActionResult Test()
        {
            var model = new ProductDao();
            var result = model.GetAllProduct();
            return View(result);
        }


        [Route("[action]")]
        public JsonResult GetData()
        {
            var model = new ProductDao();
            var result = model.GetAllProduct();
            return Json(new { rows = result });
        }

        [Route("[action]")]
        public void AddProductJson(Product entity)
        {
            try
            {
                var model = new ProductDao();
                var result = model.AddProductJson(entity);
            }
            catch (Exception)
            {

                throw;
            }
        }

        [Route("[action]")]
        public void EditProductJson(Product entity)
        {
            try
            {
                var temp = entity;
                db.Entry(temp).State = EntityState.Modified;
                db.SaveChanges();
            }
            catch (Exception)
            {

                throw;
            }
        }

        [Route("[action]")]
        public void DeleteProductJson(int id)
        {
            try
            {
                var model = new ProductDao();
                var result = model.DeleteProductCategoryJson(id);
            }
            catch (Exception)
            {

                throw;
            }
        }
    }
}

webvitinh/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Model.Dao;

namespace webvitinh.Controllers
{
    public class ProductController : Controller
    {

        public IAuthenticationSchemeProvider authenticationSchemeProvider { get; set; }
        //public ProductController(IAuthenticationSchemeProvider authenticationSchemeProvider)
        //{
        //    this.authenticationSchemeProvider = authenticationSchemeProvider;
        //}
        
        //public ProductController(IOptions<MySeting> settings)
        //{
        //    if (settings != null && settings.Value != null)
        //    {
        //        authenticationSchemeProvider = new DependencyServiceImpl(settings.Value);
        //    }
        //}


        // GET: Product
        [HttpGet("san-pham")]
        public IActionResult Index(int page = 1, int pageSize = 8)
        {
            int ToTalRecord = 0;
            var model = new ProductDao().AllProducts(ref ToTalRecord, page, pageSize);

            ViewBag.Total = ToTalRecord;
            ViewBag.Page = page;

            int maxPage = 5;
            int TotalPage = 0;

            TotalPage = (int)Math.Ceiling((double)(ToTalRecord / pageSize));
            ViewBag.TotalPage = TotalPage;
            ViewBag.MaxPage = maxPage;
            ViewBag.First = 1;
            ViewBag.Last = TotalPage;
            ViewBag.Next = page + 1;
            ViewBag.Prev = page - 1;

            return View(model);
        }

        public JsonResult ListName(string q)
        {
            var data = new ProductDao().ListName(q);
            return Json(new
            {
                data = data,
                status = true
            });
        }


        [HttpGet("Search")]
        public IActionResult Search(string keyword, int page = 1, int pageSize = 5)
        {
            int totalRecord = 0;
            var model = new ProductDao().Search(keyword, ref totalRecord, page, pageSize);

            ViewBag.Total = totalRecord;
            ViewBag.Page = page;
            ViewBag.Keyword = keyword;
            int maxPage = 5;
            int totalPage = 0;

            totalPage = (int)Math.Ceiling((double)(totalRecord / pageSize));
            ViewBag.TotalPage = totalPage;
            ViewBag.MaxPage = maxPage;
            ViewBag.First = 1;
            ViewBag.Last = totalPage;
            ViewBag.Next = page + 1;
            ViewBag.Prev = page - 1;

            return View(model);
        }

        [HttpGet("san-pham/{metatitle}-{cateid}")]
        public IActionResult Category(long cateId, int page = 1, int pageSize = 5)
        {
            var category = new ProductCategoryDao().ViewDetail(cateId);
            ViewBag.Category = category;
            int ToTalRecord = 0;
            var model = new ProductDao().ListProductByCategoryId(cateId, ref ToTalRecord, page, pageSize);

            ViewBag.Total = ToTalRecord;
            ViewBag.Page = page;

            int maxPage = 5;
            int TotalPage = 0;

            TotalPage = (int)Math.Ceiling((double)(ToTalRecord / pageSize));
            ViewBag.TotalPage = TotalPage;
            ViewBag.MaxPage = maxPage;
            ViewBag.First = 1;
            ViewBag.Last = TotalPage;
            ViewBag.Next = page + 1;
            ViewBag.Prev = page - 1;

            return View(model);
            /*var category = new CategoryDao().ViewDetail(cateid);
            ViewBag.Category = category;
            int ToTalRecord = 0;
            var model = new ProductDao().ListProductByCategoryId(cateid,ref ToTalRecord, page, pageSize);
            ViewBag.Total = ToTalRecord;
            ViewBag.Page = page;

            int maxPage = 5;
            int TotalPage = 0;

            TotalPage = (int)Math.Ceiling((double)(ToTalRecord / pageSize));
            ViewBag.TotalPage = TotalPage;
            ViewBag.MaxPage = maxPage;
            ViewBag.First = 1;
            ViewBag.Last = TotalPage;
            ViewBag.Next = page + 1;
            ViewBag.Previus = page - 1;
            return View(model);*/
        }

        [Route("[action]")]
        [HttpGet("chi-tiet/{metatitle}-{id}")]
        public IActionResult Detail(int id)
        {
            var product = new ProductDao().ViewDetail(id);
            ViewBag.Category = new ProductCategoryDao().ViewDetail(product.CategoryId.Value);
            ViewBag.RelatedProduct = new ProductDao().ListRelatedProducts(id);
            return View(product);
        }


    }
}

webvitinh/ViewComponents/ProductCategoryViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Model.Dao;
using webvitinh.Common;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace webvitinh.ViewComponents
{
    public class ProductCategoryViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var model = new ProductCategoryDao().ListAll();
            return View(model);
        }
    }
}

webvitinh/Views/Product/Category.cshtml
@model List<Model.Product>

<!-- neu muon join su dung --><!--Model.ViewModel.ProductViewModel-->
@{
    var category = (Model.ProductCategory)ViewBag.Category;
    ViewBag.Title = category.Name;
    Layout = "~/Views/Shared/_Layout.cshtml"; ;

}
<div class="content">
    <div class="content_top">
        <div class="heading">
            <h3>@category.Name</h3>
        </div>
        <div class="see">
            <p><a href="#">See all Products</a></p>
        </div>
        <div class="clear"></div>
    </div>
    <div class="section group">
        @foreach (var item in Model)
        {
            var link = "/chi-tiet/" + item.MetalTitle + "-" + item.Id;
            <div class="grid_1_of_4 images_1_of_4">
                <a href="@link"><img src="/imgaes_vitinh_2/@item.Image" alt="" /></a>
                <h2>@item.Name</h2>
                <span>@item.CategoryId</span>
                <div class="price-details">
                    <div class="price-number">
                        <p><span class="rupees">@(item.Price.HasValue ? item.Price.Value.ToString("N0") : "Liên hệ")</span></p>
                    </div>
                    <div class="add-cart">
                        <h4><a href="/them-gio-hang?productID=@item.Id&quantity=1">Add to Cart</a></h4>
                    </div>
                    <div class="clear"></div>
                </div>

            </div>
        }
        <div class="clear"></div>
        <!--Phân trang-->
        @if (ViewBag.TotalPage > 1)
        {
            var pageDisplay = (int)ViewBag.MaxPage;
            int totalPage = (int)ViewBag.TotalPage;
            int currentPage = ((int)ViewBag.Page);

            // Create numeric links
            var startPageIndex = Math.Max(1, currentPage - pageDisplay / 2);
            var endPageIndex = Math.Min(totalPage, currentPage + pageDisplay / 2);

            var link = "/san-pham/" + category.MetaTitle + "-" + category.Id;
            <nav>
                <ul class="pagination">
                    @if (currentPage > ViewBag.First)
                    {
                        <li><a href="@link?page=@ViewBag.First" title="Front page" class="first"><i class="fa fa-angle-double-left"></i></a></li>
                        <li>
                            <a href="@link?page=@ViewBag.Prev" title="Last page" class="prev"><i class="fa fa-angle-left"></i></a>
                        </li>

                    }
                    @for (int i = startPageIndex; i <= endPageIndex; i++)
                    {
                        if (currentPage == i)
                        {

                            <li> <a href="@link?page=@i" class="active" title="Page @i">@i</a></li>
                        }
                        else
                        {
                            <li><a href="@link?page=@i" title="Trang @i" class="pos">@i</a></li>
                        }
                    }
                    @if (currentPage < totalPage)
                    {
                        <li><a href="@link?page=@ViewBag.Next" class="next" title="Front page"><i class="fa fa-angle-right"></i></a></li>
                        <li> <a href="@link?page=@ViewBag.Last" class="last" title="Last page"><i class="fa fa-angle-double-right"></i></a></li>
                    }

                </ul>
            </nav>

        }
        else
        {
        }
    </div>
</div>

webvitinh/Views/Product/Detail.cshtml
@model Model.Product
@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var category = (Model.ProductCategory)ViewBag.Category;
    var relatedProducts = (List<Model.Product>)ViewBag.RelatedProduct;
}

<div class="content">
    <div class="content_top">
        <div class="back-links">
            <p><a href="index.html">Home</a> >>>> <a href="/san-pham/@category.MetaTitle-@category.Id">@category.Name</a></p>
        </div>
        <div class="clear"></div>
    </div>
    <div class="section group">
        <div class="cont-desc span_1_of_2">
            <div class="product-details">
                <div class="grid images_3_of_2">
                    <div id="container">
                        <div id="products_example">
                            <div id="products">
                                <div class="slides_container">
                                    <a href="#" target="_blank"><img src="@Model.Image" alt=" " /></a>
                                </div>
                                @*<ul class="pagination">
                                        <li><a href="#"><img src="images/thumbnailslide-1.jpg" alt=" " /></a></li>
                                        <li><a href="#"><img src="images/thumbnailslide-2.jpg" alt=" " /></a></li>
                                        <li><a href="#"><img src="images/thumbnailslide-3.jpg" alt=" " /></a></li>
                                        <li><a href="#"><img src="images/thumbnailslide-4.jpg" alt=" " /></a></li>
                                        <li><a href="#"><img src="images/thumbnailslide-5.jpg" alt=" " /></a></li>
                                        <li><a href="#"><img src="images/thumbnailslide-6.jpg" alt=" " /></a></li>
                                    </ul>*@
                            </div>
                        </div>
                    </div>
                </div>
                <div class="desc span_3_of_2">
                    <h2>@Model.Name</h2>
                    <p>@Model.Description</p>
                    <div class="price">
                        <p>Price: <span>@(Model.Price.HasValue ? Model.Price.Value.ToString("N0") : "Contact")</span></p>
                    </div>
                    <div class="available">
                        <p>Available Options :</p>
                        <ul>
                            <li>
                                Color:
                                <select>
                                    <option>Silver</option>
                                    <option>Black</option>
                                    <option>Dark Black</option>
                                    <option>Red</option>
                                </select>
                            </li>
                            <li>
                                Size:<select>
                                    <option>Large</option>
                                    <option>Medium</option>
                                    <option>small</option>
                                    <option>Large</option>
                                    <option>small</option>
                                </select>
                            </li>
                            <li>
                                Quality:<select>
                                    <option>1</option>
                                    <option>2</option>
                                    <option>3</option>
                                    <option>4</option>
                                    <option>5</option>
                                </select>
                            </li>
                        </ul>
                    </div>
                    <div class="share-desc">
                        <div class="share">
                            <p>Share Product :</p>
                            <ul>
                                <li><a href="#"><img src="images/facebook.png" alt="" /></a></li>
                                <li><a href="#"><img src="images/twitter.png" alt="" /></a></li>
                            </ul>
                        </div>
                        <div class="button"><span><a href="/them-gio-hang?productID=@Model.Id&quantity=1">Add to Cart</a></span></div>
                        <div class="clear"></div>
                    </div>
                    <div class="wish-list">
                        <ul>
                            <li class="wish"><a href="#">Add to Wishlist</a></li>
                            <li class="compare"><a href="#">Add to Compare</a></li>
                        </ul>
                    </div>
                </div>
                <div class="clear"></div>
            </div>
            <div class="product_desc">
                <div id="horizontalTab">
                    <ul class="resp-tabs-list">
                        <li>Product Details</li>
                        <div class="clear"></div>
                    </ul>
                    <div class="resp-tabs-container">
                        <div class="product-desc">
                            @Html.Raw(Model.Detail)
                        </div>
                    </div>
                </div>
            </div>
            <script type="text/javascript">
                $(document).ready(function () {
                    $('#horizontalTab').easyResponsiveTabs({
                        type: 'default', //Types: default, vertical, accordion
                        width: 'auto', //auto or any width like 600px
                        fit: true   // 100% fit in a container
                    });
                });
            </script>
            <div class="content_bottom">
                <div class="heading">
                    <h3>Related Products</h3>
                </div>
                <div class="see">
                    <p><a href="/san-pham">See all Products</a></p>
                </div>
                <div class="clear"></div>
            </div>
            <div class="section group">
                @foreach (var item in relatedProducts)
                {
                    var url = "/chi-tiet/" + item.MetalTitle + "-" + item.Id;
                    <div class="grid_1_of_4 images_1_of_4">
                        <a href="@url"><img src="/imgaes_vitinh_2/@item.Image" alt=""></a>
                        <div class="price" style="border:none">
                            <div class="add-cart" style="float:none">
                                <h4><a href="@url">Add to Cart</a></h4>
                            </div>
                            <div class="clear"></div>
                        </div>
                    </div>
                }
                <div class="grid_1_of_4 images_1_of_4">
                    <a href="#"><img src="images/new-pic1.jpg" alt=""></a>
                    <div class="price" style="border:none">
                        <div class="add-cart" style="float:none">
                            <h4><a href="#">Add to Cart</a></h4>
                        </div>
                        <div class="clear"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="rightsidebar span_3_of_1">
            @await Component.InvokeAsync("ProductCategory")
            <div class="subscribe">
                <h2>Newsletters Signup</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod.......</p>
                <div class="signup">
                    <form>
                        <input type="text" value="E-mail address" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'E-mail address';"><input type="submit" value="Sign up">
                    </form>
                </div>
            </div>
            <div class="community-poll">
                <h2>Community POll</h2>
                <p>What is the main reason for you to purchase products online?</p>
                <div class="poll">
                    @*<form>
                        <ul>
                            <li>
                                <input type="radio" name="vote" class="radio" value="1">
                                <span class="label"><label>More convenient shipping and delivery </label></span>
                            </li>
                            <li>
                                <input type="radio" name="vote" class="radio" value="2">
                                <span class="label"><label for="vote_2">Lower price</label></span>
                            </li>
                            <li>
                                <input type="radio" name="vote" class="radio" value="3">
                                <span class="label"><label for="vote_3">Bigger choice</label></span>
                            </li>
                            <li>
                                <input type="radio" name="vote" class="radio" value="5">
                                <span class="label"><label for="vote_5">Payments security </label></span>
                            </li>
                            <li>
                                <input type="radio" name="vote" class="radio" value="6">
                                <span class="label"><label for="vote_6">30-day Money Back Guarantee </label></span>
                            </li>
                            <li>
                                <input type="radio" name="vote" class="radio" value="7">
                                <span class="label"><label for="vote_7">Other.</label></span>
                            </li>
                        </ul>
                    </form>*@
                </div>
            </div>
        </div>
    </div>
</div>
    </div>

webvitinh/Views/Product/Index.cshtml
@model List<Model.Product>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="content">
    <div class="content_top">
        @*<div class="heading">
            <h3>@category.Name</h3>
        </div>*@
        <div class="see">
            <p><a href="#">See all Products</a></p>
        </div>
        <div class="clear"></div>
    </div>
    <div class="section group">
        @foreach (var item in Model)
        {
            var link = "/chi-tiet/" + item.MetalTitle + "-" + item.Id;
            <div class="grid_1_of_4 images_1_of_4">
                <a href="@link"><img src="/imgaes_vitinh_2/@item.Image" alt="" /></a>
                <h2>@item.Name</h2>
                <span>@item.CategoryId</span>
                <div class="price-details">
                    <div class="price-number">
                        <p><span class="rupees">@(item.Price.HasValue ? item.Price.Value.ToString("N0") : "Liên hệ")</span></p>
                    </div>
                    <div class="add-cart">
                        <h4><a href="/them-gio-hang?productID=@item.Id&quantity=1">Add to Cart</a></h4>
                    </div>
                    <div class="clear"></div>
                </div>

            </div>
        }
        <div class="clear"></div>
        <!--Phân trang-->
        @if (ViewBag.TotalPage > 1)
        {
            var pageDisplay = (int)ViewBag.MaxPage;
            int totalPage = (int)ViewBag.TotalPage;
            int currentPage = ((int)ViewBag.Page);

            // Create numeric links
            var startPageIndex = Math.Max(1, currentPage - pageDisplay / 2);
            var endPageIndex = Math.Min(totalPage, currentPage + pageDisplay / 2);

            var link = "/san-pham/";
            <nav>
                <ul class="pagination">
                    @if (currentPage > ViewBag.First)
                    {
                        <li><a href="@link?page=@ViewBag.First" title="Front page" class="first"><i class="fa fa-angle-double-left"></i></a></li>
                        <li>
                            <a href="@link?page=@ViewBag.Prev" title="Last page" class="prev"><i class="fa fa-angle-left"></i></a>
                        </li>

                    }
                    @for (int i = startPageIndex; i <= endPageIndex; i++)
                    {
                        if (currentPage == i)
                        {

                            <li> <a href="@link?page=@i" class="active" title="Page @i">@i</a></li>
                        }
                        else
                        {
                            <li><a href="@link?page=@i" title="Trang @i" class="pos">@i</a></li>
                        }
                    }
                    @if (currentPage < totalPage)
                    {
                        <li><a href="@link?page=@ViewBag.Next" class="next" title="Front page"><i class="fa fa-angle-right"></i></a></li>
                        <li> <a href="@link?page=@ViewBag.Last" class="last" title="Last page"><i class="fa fa-angle-double-right"></i></a></li>
                    }

                </ul>
            </nav>

        }
        else
        {
        }
    </div>
</div>

webvitinh/Views/Product/Search.cshtml
@model List<Model.ViewModel.ProductViewModel>
@{
    ViewBag.Title = "Kết quả tìm kiếm";
    Layout = "~/Views/Shared/_Layout.cshtml";

}
<div class="content">
    <div class="content_top">
        <div class="heading">
            <h3>Kết quả tìm kiếm theo từ khoá: @ViewBag.Keyword</h3>
        </div>
        <div class="see">
            <p><a href="#">See all Products</a></p>
        </div>
        <div class="clear"></div>
    </div>
    <div class="section group">
        @if (Model.Count > 0)
        {
            foreach (var item in Model)
            {
                var link = "/chi-tiet/" + item.MetaTitle + "-" + item.ID;
        <div class="grid_1_of_4 images_1_of_4">
            <a href="@link"><img src="/imgaes_vitinh_2/@item.Images" alt="" /></a>
            <h2>@item.Name</h2>
            <span>@item.CateName</span>
            <div class="price-details">
                <div class="price-number">
                    <p><span class="rupees">@(item.Price.HasValue ? item.Price.Value.ToString("N0") : "Liên hệ")</span></p>
                </div>
                <div class="add-cart">
                    <h4><a href="/gio-hang/@item.ID">Thêm vào giỏ</a></h4>
                </div>
                <div class="clear"></div>
            </div>

        </div>
            }
        <div class="clear"></div>
 <!--Phân trang-->
            if (ViewBag.TotalPage > 1)
            {
                var pageDisplay = (int)ViewBag.MaxPage;
                int totalPage = (int)ViewBag.TotalPage;
                int currentPage = ((int)ViewBag.Page);

                // Create numeric links
                var startPageIndex = Math.Max(1, currentPage - pageDisplay / 2);
                var endPageIndex = Math.Min(totalPage, currentPage + pageDisplay / 2);

                var link = "/Search?keyword=" + ViewBag.Keyword;
        <nav>
            <ul class="pagination">
                @if (currentPage > ViewBag.First)
                        {
                <li><a href="@link&page=@ViewBag.First" title="Trang đầu" class="first"><i class="fa fa-angle-double-left"></i></a></li>
                <li>
                    <a href="@link&page=@ViewBag.Prev" title="Trang trước" class="prev"><i class="fa fa-angle-left"></i></a>
                </li>

                        }
                @for (int i = startPageIndex; i <= endPageIndex; i++)
                    {
                        if (currentPage == i)
                        {

                <li> <a href="@link&page=@i" class="active" title="Trang @i">@i</a></li>
                            }
                            else
                            {
                <li><a href="@link&page=@i" title="Trang @i" class="pos">@i</a></li>
                            }
                        }
                @if (currentPage < totalPage)
                    {
                <li><a href="@link&page=@ViewBag.Next" class="next" title="Trang sau"><i class="fa fa-angle-right"></i></a></li>
                <li> <a href="@link&page=@ViewBag.Last" class="last" title="Trang cuối"><i class="fa fa-angle-double-right"></i></a></li>
                        }

            </ul>
        </nav>

            }
        }
        else
        {
        <span>Không có bản ghi nào</span>
        }


    </div>
</div>